/*
 * Copyright (c) 2025, CATIE
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_SENSOR_HERACLES224G_HERACLES224G_H_
#define ZEPHYR_DRIVERS_SENSOR_HERACLES224G_HERACLES224G_H_

#endif /* ZEPHYR_DRIVERS_SENSOR_HERACLES224G_HERACLES224G_H_ */
